
name: build matrix demo1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.9"
          - "4.0"
          - "4.1"
          - "4.2"
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo success
